---
title: "michael_file"
author: "doraaobodo"
date: "2020-07-13"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r Load Libraries}
library(data.table)
library(usmap)
library(ggplot2)
library(workflowr)
```

```{r processing}
foi150 = fread(file.path('data', 'foia_150k_plus.csv'))
foi150[, fips := usmap::fips(state = State)]

foiSummary = foi150[, lapply(.SD, sum, na.rm = TRUE), by = State, .SDcols = c('JobsRetained')]
foiSummary[, fips := usmap::fips(state = State)]
foiSummary = foiSummary[!is.na(fips), ]

foiDT = data.table(
  fips = as.numeric(foiSummary$fips),
  X = as.numeric(foiSummary$JobsRetained)
)
statepop$fips = as.numeric(statepop$fips)

popFoiDT = foiDT
popFoiDT = merge(foiDT, statepop, by = 'fips')
popFoiDT[, jobsPerPerson := X / pop_2015]


popDT = data.table(
  fips = popFoiDT$fips,
  X = popFoiDT$jobsPerPerson
)
```

```{r plotting, echo=TRUE}

p = plot_usmap(data = foiDT, values = 'X') +
  scale_fill_continuous(low = 'white', high = 'blue', name = 'Jobs Retained',
                        labels = scales::comma)

p
```

```{r plotting pop adjusted, echo = TRUE}
popAdjPlot = plot_usmap(data = popDT, values = 'X' ) +
    scale_fill_continuous(low = 'white', high = 'blue', name = 'Jobs Retained/Person',
                        labels = scales::comma)

popAdjPlot
```
